### ISSUE TITLE
Support communityPGLMMs?

### ISSUE THREAD

**Issue by daijiang** [arives/rr2#1]
Is it possible to support `communityPGLMM` models?

Can `communityPGLMM` models predict species abundance?

**Comment by arives** [comment]
Daijiang,

For continuous data, the easiest thing would be to use R2.lr. For binary data, the predictions are in the values of mu, so these can be used to calculate R2.ce in the same way as in binaryPGLMM. It’s a little unfortunately that you can’t use the same R2 for both cases. Oh well.

Cheers, Tony

**Comment by daijiang** [comment]
first commit  0b7baa6
