### ISSUE TITLE
Suggestion: Extend R2 calculation to gls() objects of the nlme package

### ISSUE THREAD

**Issue by AEgit** [arives/rr2#12]
It would be nice if the R2 calculations could be extended to gls() objects of the _nlme_ package (https://cran.r-project.org/web/packages/nlme/index.html), which is probably more widely used than the more specialised _phylolm_ package. Phylogenetic correlation structures are often generated for gls() objects using the corClasses of the _ape_ package (e.g., corBrownian() function).

**Comment by arives** [comment]
I agree, it would be useful. The problem is that the objects generated by gls() don't contain all the information needed. One option would be to have the user supply them separately, but this gets a little awkward. Do you think the advantages outweigh the disadvantages (having a longer list of things that might have to be specified depending on the function used)?

Cheers, Tony

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by AEgit** [comment]
I think the advantages would outweigh the disadvantages since quite a few people would be keen to use the rr2 package but are probably going to continue to use gls() objects (for various reasons). Obviously, this is just a suggestion coming from a user background: I am not sure how much effort it would require to implement this. But I thought it would be good to let you know about this potential improvement.

**Comment by arives** [comment]
Just a quick thought since you emailed from github. Did you know that rr2 is now on CRAN?

Cheers, Tony

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by AEgit** [comment]
Yes, I think during the installation I already went for the CRAN version.

Cheers!

**Comment by arives** [comment]
Just to let you know, Daijiang and I just updated rr2 for gls objects. It was easier than I thought, and I should have done it earlier. Thanks for asking!

It might take a day or two for it to get into CRAN. The version is 1.0.1.

**Comment by AEgit** [comment]
Thank you very much! Indeed, I think many people will appreciate this update.

**Comment by arives** [comment]
I just got word that rr2 should be on CRAN in 24 hours.

**Comment by AEgit** [comment]
Thanks again! Yes, the source is already available from CRAN (version 1.0.1 can therefore already be installed directly from CRAN). Binaries are currently not available from CRAN, but, as you say, they will probably be available soon.
I made a quick test with some gls() models I had - so far everything seems to work fine. Thank you very much!

**Comment by arives** [comment]
Great. And thanks for letting me know. Any gls() model should working, including time-series models, etc. That could be interesting to explore at some point.

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by AEgit** [comment]
Hmmm, I think the issue needs to be re-opened.
Apparently, non-ultrametric trees currently do not work when using a gls() model. I provide an example below:

```
library(ape)
library(phytools)
library(nlme)
library(rr2)
# #Set seed (for repeatability)
set.seed(1)
# #Simulate a non-ultrametric tree
tree <- rtree(n = 100) # #This tree is not ultrametric!
# #Simulate some data
x <- fastBM(tree)
y <- 0.75*x + fastBM(tree, 0.2)
# #Compute weights (necessary for non-ultrametric trees)
w <- diag(vcv.phylo(tree))
# #Fit gls model
fit <- gls(y ~ x,data = data.frame(x, y), 
           correlation = corBrownian(1, tree),
           weights = varFixed(~w))
fit
R2(mod = fit, phy = tree) # # THIS DOES NOT WORK!
# #We get the following error message:
# #'Error in divide.matrix(mat) : Matrix is not block-diagonal'
  

# #Ok, now let's make our tree ultrametric
u.tree <- compute.brlen(tree, method = 'Grafen', power = 1) # #This tree is ultrametric!
# #Fit gls model again
u.fit <- gls(y ~ x,data = data.frame(x, y), 
           correlation = corBrownian(1, u.tree))
u.fit
R2(mod = u.fit, phy = u.tree)  # # THIS DOES WORK!
```
When using the R2() function for a gls() model applied to a non-ultrametric tree, I end up with the following error message:
`
Error in divide.matrix(mat) : Matrix is not block-diagonal`

Any thoughts on this?

**Comment by arives** [comment]
Thanks! This is strange. I'm not going to have a chance to look at it for a while. Presumably the R2.lik version of R2 will work, if you need something immediately.

Cheers, Tony


______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by AEgit** [comment]
Hi Tony,

thank you for the quick reply. I've tried the individual functions of R2(). Both R2.lik() and R2.pred() appear to work.
With the simulated data from above I get:

```
R2.lik(mod = fit) # #Result: [1] 0.5960893
R2.pred(mod = fit, phy = tree) # #Result: [1] 0.7097763
```

Only R2.resid() does not seem to work:

`R2.resid(mod = fit, phy = tree) # #Result: Error in divide.matrix(mat) : Matrix is not block-diagonal`

No worries, I won't need it immediately. But maybe you can re-open the Github issue so that this problem is not forgotten?

Thanks again for your help!

**Comment by ctencaten** [comment]
Hi,

I'm with the same problem as AEgit, while I'm able to use both R2.lik and R2.pred fuctions without problem, when using R2.resid I also get this error message Error in divide.matrix(mat) : Matrix is not block-diagonal. 

It seems that this problem occurs when using the vcv2phylo function from ape package. Apparently it happens when the matrix has no values lower than the one used in the tolerance argument, which then produces NA and consequently the error in the divide.matrix function which is inside the vcv2phylo function. I was not able find any solution for it though. Have you guys found any workaround it?

Cheers

**Comment by AEgit** [comment]
Hi @ctencaten,

my "workaround" was to just ignore the R2.resid() function and to only use R2.lik() and R2.pred(). Indeed, it would be nice to also have R2.resid(), but that depends on whether Tony @arives or Daijiang @daijiang have time to implement it.

**Comment by arives** [comment]
Sorry about this problem. There is also another problem when using gls() and non-contemporaneous tips. I'll try to look at these in the next few days.

Thanks to both of you!

**Comment by AEgit** [comment]
Maybe it would be better to open the issue again?

Thank you very much for your help!

**Comment by ctencaten** [comment]
Hi @AEgit , I think using R2.pred and R2.lid is actually a good alternative while we can't use R2.resid, I'll do that as well.

Hi Tony, thank you very much for the quick reply and for your help.

Best

**Comment by arives** [comment]
ctencaten and AEgit,

I just updated R2.resid. It will now do gls models with non-ultrametric trees. I have a note in the documentation that you will get an error if you don't use weights=varFixed in the gls() fit (which people should be doing to get the right answer. I couldn't find a nice way to catch this error: tryCatch didn't work. But at least it is in the documentation example.

ctencaten, I'm not sure about your error. For a work around, does rescaling the edge.lengths make sense. 

What do you think?

Cheers, Tony

**Comment by AEgit** [comment]
Hi Tony,

amazing, thank you very much! I can confirm that the new version of "rr2" works with the non-ultrametric tree example I provided. Later on I might have time to test it also with my actual data, but I reckon this should work, since I have always used weights = varfixed for my gls() fits using non-ultrametric treess.

Cheers!

**Comment by ctencaten** [comment]
Hi Tony,

Thanks for updating the function. I think your suggestion does make sense, I have done it and the function worked perfectly.

Cheers!

**Comment by AEgit** [comment]
Ok, so after some testing, I managed to produce one example, where both `R2.pred()` and `R2.resid()` show an unexpected (but maybe correct?) behaviour. The input files are provided herein:

[R2_Issue.zip](https://github.com/arives/rr2/files/3734595/R2_Issue.zip)


Using the input files "myGLSdata.csv" and "mytree.tree", the following code will produce the unexpected behaviour:

```

# #Part that is uploaded to GitHub
library(ape)
library(nlme)
library(rr2)

# #Import our data
mytree <- read.tree("mytree.tree")
myGLSdata <- read.csv("myGLSdata.csv")
rownames(myGLSdata) <- myGLSdata[["Taxa"]]


# #Now order row names of data file according to tip labels of input tree
myGLSdata.ord <- myGLSdata[match(mytree$tip.label,rownames(myGLSdata)),]

# #Compute weights: necessary for non-ultrametric trees when using gls()
gls.weights <- as.data.frame(diag(vcv.phylo(mytree)))
colnames(gls.weights) <- "gls.w" # #Replace column name with "gls.w"
gls.weights[["Taxa"]] <- rownames(gls.weights) # #Add "Taxa" column (needed for merge operation)
gls.weights

# #Merge ordered dataset and weights
myGLSdata.ord <- merge(myGLSdata.ord, gls.weights, by = "Taxa", sort = FALSE)
rownames(myGLSdata.ord) <- myGLSdata.ord[["Taxa"]]
myGLSdata.ord

# #Compute model (estimating lambda + using "REML")
mymodel <- gls(M1 ~ M2, data = myGLSdata.ord, #na.action = na.exclude,
             correlation = corPagel(1, mytree, fixed = FALSE),
             weights = varFixed(~gls.w), 
             method="REML")

R2.lik(mymodel) # #Ok, this works: 0.9622262
R2.pred(mymodel) # #This appears really weird: -1804.571
R2.resid(mymodel) # #This does not work "Error in divide.matrix(mat) : Matrix is not block-diagonal"
# #(probably because lambda > 1???)


```

1. Note, that `R2.lik` produces an R2 value, that (at least at first glance) appears fine.

2. `R2.pred` produces an R2 value, that seems really weird: -1804.571
Something must have gone wrong here: Any ideas? Maybe a convergence issues of the gls function (but in this particular case no such error message is reported to the user)?

3. `R2.resid` does not work at all but gives the error: "`Error in divide.matrix(mat) : Matrix is not block-diagonal`". Could this be caused by the estimated lambda value, which is larger than 1?
We could ask, whether a value of lambda > 1 makes sense (but see, for example, the discussions here: https://grokbase.com/t/r/r-sig-phylo/113s5mhjgg/pagels-lambda-greater-than-one; http://blog.phytools.org/2016/01/phylogenetic-regression-when-estimated.html). But if we reject the possibility of lambda being >1, then `R2.resid` should probably give a meaningful warning/error message.

**Comment by AEgit** [comment]
@arives Any thoughts on this latest issue (https://github.com/arives/rr2/issues/12#issuecomment-542709945)?

**Comment by daijiang** [comment]
Negative R2 values are possible mathematically. Here, removing some species (Taxon 3-8) changes the fit the most, thus large variance and SSE.pred, which in turn resulted the -1804 R2.pred result. But it is mathematically correct

**Comment by AEgit** [comment]
@daijiang : Cheers! What about the `R2.resid` error message?

**Comment by daijiang** [comment]
Error message of `R2.resid` likely because the failure to recover the original phylogenetic var-cov matrix from the regression. One potential easy fix is to ask users to provide the phylogeny along with the fitted model.

**Comment by AEgit** [comment]
Hmmm, but why would that appear only in specific cases? Usually this works - just in this particular case I encounter this error. Couldn't it be related to the fact that a lambda value >1 was estimated?
