### ISSUE TITLE
Error estimating R2 from the pglmm (phyr) model

### ISSUE THREAD

**Issue by Flaiba** [arives/rr2#18]
Hello, I have a little problem getting the R2 for a model (pglmm) produced by the package phyr.
I suppose the problem is how is defined the variable response in my model, because in the pglmm model the variable response is defined by success and failure, meanwhile, for estimating the R2 it will be necessary that the response variable will be codified as numeric, but in this last case, I need to define a weight for the number of trials.   
My model is 
M=pglmm(cbind(Neoplasia, Nodeadbycancer) ~ LitterSize2 + (1|OLRE), data = Lit2, family = "binomial",cov_ranef = list(sp = phy),add.obs.re = FALSE) where the Neoplasia are the successes and Nodeadbycancer are the fails. I am trying to model the incidence of cancer in a group of mammal species.

R2(mod = M)
Models of class pglmm do not have a R2_resid method.
Error in eval(family$initialize) : y values must be 0 <= y <= 1

How I can estimate the R2?

Thanks for your time.

**Comment by arives** [comment]
Sorry I was slow getting to this. The github version is now updated and should work. The problem was the call to glm() in the rr2 code that is used for the reduced model cbind(y, size-y) ~ 1. 

Thanks for letting me know about this!
