### ISSUE TITLE
log(v)?

### ISSUE THREAD

**Issue by daijiang** [arives/rr2#2]
https://github.com/arives/rr2/blob/9794299f8ff7215002980b7683206ac89a258277/R/r2_resid.R#L122

shouldn't this (and line 130, 185, 203, 215) be `log(v)`? @arives .

**Comment by arives** [comment]
Daijiang,

Thanks for catching this. I couldn't make edits to that branch on github, but the code for lines 122-130 should be

if(family(mod)[1] == "binomial") Yhat <- log(mu/(1 - mu))
if(family(mod)[1] == "poisson") Yhat <- log(mu)

sig2e <- pi^2/3
SSE.resid <- sig2e/(var(Yhat) + sig2e)

mu.r <- mod.r$fitted.values
if(family(mod.r)[1] == "binomial") Yhat.r  <- log(mu.r/(1 - mu.r))
if(family(mod.r)[1] == "poisson") Yhat.r <- log(mu.r)

sig2e.r <- pi^2/3


Tony
______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
9951797
