### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by sastoudt** [arives/rr2#5]
For JOSS Review: https://github.com/openjournals/joss-reviews/issues/1028

- [x] In LICENSE.md finish at "END OF TERMS AND CONDITIONS"
- [x] "add information on how to contact you by electronic and paper mail" in the headers of the source files

**Comment by daijiang** [comment]
Hi @sastoudt,
For the first point, you mean we should remove all things after "END OF TERMS AND CONDITIONS" in LICENSE.md?
What do you mean by the second point? I think the contact information is already in the DESCRIPTION file and that should be enough?

**Comment by sastoudt** [comment]
First point: Yes, looking [here](https://opensource.org/licenses/GPL-3.0) I think everything after END OF TERMS AND CONDITIONS is for the authors rather than the reader of the license.

Second point: You're right, I missed the e-mails in the DESCRIPTION.

**Comment by daijiang** [comment]
Thanks. Updated.
